/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccountantRouteImport } from './routes/accountant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerReportsRouteImport } from './routes/owner/reports'
import { Route as OwnerProjectsRouteImport } from './routes/owner/projects'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as OwnerLayoutRouteImport } from './routes/owner/_layout'
import { Route as ManagerDashboardRouteImport } from './routes/manager/dashboard'
import { Route as AccountantDashboardRouteImport } from './routes/accountant/dashboard'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountantRoute = AccountantRouteImport.update({
  id: '/accountant',
  path: '/accountant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerReportsRoute = OwnerReportsRouteImport.update({
  id: '/owner/reports',
  path: '/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProjectsRoute = OwnerProjectsRouteImport.update({
  id: '/owner/projects',
  path: '/owner/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLayoutRoute = OwnerLayoutRouteImport.update({
  id: '/owner/_layout',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ManagerRoute,
} as any)
const AccountantDashboardRoute = AccountantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AccountantRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/owner': typeof OwnerLayoutRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/projects': typeof OwnerProjectsRoute
  '/owner/reports': typeof OwnerReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/owner': typeof OwnerLayoutRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/projects': typeof OwnerProjectsRoute
  '/owner/reports': typeof OwnerReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accountant': typeof AccountantRouteWithChildren
  '/login': typeof LoginRoute
  '/manager': typeof ManagerRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/accountant/dashboard': typeof AccountantDashboardRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/owner/_layout': typeof OwnerLayoutRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/projects': typeof OwnerProjectsRoute
  '/owner/reports': typeof OwnerReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accountant'
    | '/login'
    | '/manager'
    | '/projects'
    | '/register'
    | '/accountant/dashboard'
    | '/manager/dashboard'
    | '/owner'
    | '/owner/dashboard'
    | '/owner/projects'
    | '/owner/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accountant'
    | '/login'
    | '/manager'
    | '/projects'
    | '/register'
    | '/accountant/dashboard'
    | '/manager/dashboard'
    | '/owner'
    | '/owner/dashboard'
    | '/owner/projects'
    | '/owner/reports'
  id:
    | '__root__'
    | '/'
    | '/accountant'
    | '/login'
    | '/manager'
    | '/projects'
    | '/register'
    | '/accountant/dashboard'
    | '/manager/dashboard'
    | '/owner/_layout'
    | '/owner/dashboard'
    | '/owner/projects'
    | '/owner/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountantRoute: typeof AccountantRouteWithChildren
  LoginRoute: typeof LoginRoute
  ManagerRoute: typeof ManagerRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  OwnerLayoutRoute: typeof OwnerLayoutRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerProjectsRoute: typeof OwnerProjectsRoute
  OwnerReportsRoute: typeof OwnerReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accountant': {
      id: '/accountant'
      path: '/accountant'
      fullPath: '/accountant'
      preLoaderRoute: typeof AccountantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/reports': {
      id: '/owner/reports'
      path: '/owner/reports'
      fullPath: '/owner/reports'
      preLoaderRoute: typeof OwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/projects': {
      id: '/owner/projects'
      path: '/owner/projects'
      fullPath: '/owner/projects'
      preLoaderRoute: typeof OwnerProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/_layout': {
      id: '/owner/_layout'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/accountant/dashboard': {
      id: '/accountant/dashboard'
      path: '/dashboard'
      fullPath: '/accountant/dashboard'
      preLoaderRoute: typeof AccountantDashboardRouteImport
      parentRoute: typeof AccountantRoute
    }
  }
}

interface AccountantRouteChildren {
  AccountantDashboardRoute: typeof AccountantDashboardRoute
}

const AccountantRouteChildren: AccountantRouteChildren = {
  AccountantDashboardRoute: AccountantDashboardRoute,
}

const AccountantRouteWithChildren = AccountantRoute._addFileChildren(
  AccountantRouteChildren,
)

interface ManagerRouteChildren {
  ManagerDashboardRoute: typeof ManagerDashboardRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerDashboardRoute: ManagerDashboardRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountantRoute: AccountantRouteWithChildren,
  LoginRoute: LoginRoute,
  ManagerRoute: ManagerRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  OwnerLayoutRoute: OwnerLayoutRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerProjectsRoute: OwnerProjectsRoute,
  OwnerReportsRoute: OwnerReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
